### ISSUE TITLE
Fix permissions in ban/kick commands

### ISSUE THREAD

**Issue by comp500** [edgeboyo/kirkbot#15]
These commands have a role check for a role that doesn't exist e.g.

```js
if (!message.member.roles.some(r => ["Administrator"].includes(r.name))) {
```

Should this be changed to a `hasPermission("ADMINISTRATOR")` check, or a check for a valid role?

**Comment by edgeboyo** [comment]
yeah `hasPermission("ADMINISTRATOR")` is way better. I'll change those to the correct one

**Comment by edgeboyo** [comment]
I think this will be a massive pain if anyone ever wants to use the bot
outside of ChatSoc. It's best we kept this as hasPermission
