### ISSUE TITLE
Fix invall command

### ISSUE THREAD

**Issue by edgeboyo** [edgeboyo/kirkbot#19]
I added the command to get invites to all servers for the admins of ChatSoc.

But it keeps throwing this into DMs: 

```
Invites to all servers:
Kirk_Irl[object Promise]
```

Find the reason and fix

**Comment by comp500** [comment]
Looks fun, I'll see what I can do in a bit

**Comment by edgeboyo** [comment]
As mentioned it works for #general but not any other channel. Might be worth fixing
