### ISSUE TITLE
Put on a time limit for non-mods/non-admins

### ISSUE THREAD

**Issue by edgeboyo** [edgeboyo/kirkbot#22]
Put the limit on commands like !ping and !listall so they can't spam the server. Just ignore excess commands

**Comment by comp500** [comment]
`if (queue.size() <= 5) queue.enqueue(command)`

**Comment by edgeboyo** [comment]
Yeah, I was thinking that but we kind of have two classes of messages. Ones that go to DMs like help or invall and ones that go to chat like kirk or ping. Just need to sort out which is which and decide how we should work on them.

**Comment by edgeboyo** [comment]
The thing we have on Welcome messages would be the best, but it really would be a mess if we made that everywhere
